### ISSUE TITLE
Linking Assemblies doesn't work

### ISSUE THREAD

**Issue by Dimabiz** [halkar/xamarin-range-slider#47]
After Add Xamarin.RangeSlider to Xamarin.Android project, i have problem with copilate realese version (Link SDK Assemblies):
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'Android.Graphics.Color Android.Content.Res.Resources::GetColor(System.Int32,Android.Content.Res.Resources/Theme)' (defined in 'Xamarin.RangeSlider.Droid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') from 'Xamarin.RangeSlider.Droid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve Android.Graphics.Color Android.Content.Res.Resources::GetColor(System.Int32,Android.Content.Res.Resources/Theme)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Samson_Lenses.Droid
```			

Can you help me?

**Comment by halkar** [comment]
@Dimabiz by any chance do you have a sample project to reproduce the issue?

**Comment by Dimabiz** [comment]
@halkar my project is commercial, I can not show code, sorry. I solved the problem, in source code range-slider i replace all "a.GetColor" in RangeSliderControl.cs, on static Color value.
P.S. Sorry for my English.

**Comment by halkar** [comment]
@Dimabiz which minimum and target android version are you using?

**Comment by Dimabiz** [comment]
minimum - API 15 (Android 4.0.3)
target - API 21 (Android 5.0)

**Comment by halkar** [comment]
Thanks @Dimabiz I will investigate.

**Comment by halkar** [comment]
Fixed in https://github.com/halkar/xamarin-range-slider/pull/57
